# Generated by Django 3.1.2 on 2021-03-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente_text', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default=0)),
                ('medida', models.CharField(max_length=200)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandareceita.receita')),
            ],
        ),
    ]
