# Generated by Django 3.1.2 on 2021-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandareceita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
