# Generated by Django 3.1.2 on 2021-03-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandareceita', '0003_auto_20210303_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='medida',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
