# Generated by Django 3.1.2 on 2021-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandareceita', '0005_auto_20210303_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='ingrediente_entities',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
