# Generated by Django 3.1.2 on 2021-03-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandareceita', '0006_ingrediente_ingrediente_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='receita',
            name='receita_text',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='receita',
            name='receita_title',
            field=models.CharField(default='', max_length=400),
        ),
    ]
