# Generated by Django 3.1.2 on 2021-03-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandareceita', '0008_auto_20210304_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade_text',
            field=models.CharField(default='-1', max_length=200),
        ),
    ]
