# Generated by Django 3.1.2 on 2021-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandareceita', '0009_auto_20210304_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='receita_completa',
            field=models.BooleanField(default=False),
        ),
    ]
